service: fields # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::*"

functions:
  fields:
    handler: handler.fields
    timeout: 30
    events:
      - http:
          path: fields
          method: get
          cors: true

  coords-upload:
    handler: handler.fieldCreate
    timeout: 30
    events:
      - http:
          path: field
          method: post
          cors: true

  match:
    handler: handler.match
    timeout: 60
    events:
      - s3:
          bucket: epam-jam1
          event: s3:ObjectCreated:*
          rules:
              - prefix: fields/
              - suffix: meta.json